config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	root :to => redirect('/urls/new')
	resources :urls
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
		validates_presence_of :original , default: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

	def index
		@urls = Url.all
	end
	def show	
	url = Url.where(:random_id => params[:id]).first
		if url
		redirect_to url.original
	else
			render action: "index"
		end
	end
	def new
		@url = Url.new
		letters = [('a'..'z'), ('A'..'Z')].map { |i| i.to_a }.flatten
		@url.random_id = (0..8).map{ letters[rand(letters.length)] }.join
	end
	def urls_params
		params.require(:url).permit(:original, :random_id)
	end
	def create
		@url = Url.new(urls_params)
		if @url.save
			redirect_to urls_path
		else
			render action: "new"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>URLShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<h2>URL-shortner </h2>

<% @urls.each do |url|%>
		<p>
		<%= link_to url.random_id, url_path("url.id => url.random_id") %> => <%= url.original %>	
		</p>


<% end %>

	<%= link_to "Shorten_url" , new_url_path %>

app/views/urls/new.html.erb
<h2> Shorten-url </h2>
<%= form_for @url do |f| %>
	<% if @url.errors.any? %>
	<h3> Errors: </h3>
	<ul>
		<% @url.errors.full_messages.each do |msg| %>
			<li> <%= msg %></li>
			<% end %>
		</ul>
		<% end %>
			<p>
		<%= f.label :original %> : <%= f.text_field :original %>
	</p>
	

	<%= f.hidden_field :random_id , :value => @url.random_id %><br/>

	<%= f.submit %>

<% end %>